//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harmonic {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Harmonic.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 avc extradata not found 的本地化字符串。
        /// </summary>
        internal static string avc_extradata_not_found {
            get {
                return ResourceManager.GetString("avc_extradata_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 codecId must be a video codecId 的本地化字符串。
        /// </summary>
        internal static string codecId_must_be_a_video_codecId {
            get {
                return ResourceManager.GetString("codecId must be a video codecId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 empty publishing name 的本地化字符串。
        /// </summary>
        internal static string empty_publishing_name {
            get {
                return ResourceManager.GetString("empty_publishing_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 flv screen video is not supported 的本地化字符串。
        /// </summary>
        internal static string flv_screen_video_is_not_supported {
            get {
                return ResourceManager.GetString("flv_screen_video_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 frame should not be null 的本地化字符串。
        /// </summary>
        internal static string frame_should_not_be_null {
            get {
                return ResourceManager.GetString("frame_should_not_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not supported codec 的本地化字符串。
        /// </summary>
        internal static string not_supported_codec {
            get {
                return ResourceManager.GetString("not_supported_codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not supported publishing type 的本地化字符串。
        /// </summary>
        internal static string not_supported_publishing_type {
            get {
                return ResourceManager.GetString("not_supported_publishing_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not valid 的本地化字符串。
        /// </summary>
        internal static string not_valid {
            get {
                return ResourceManager.GetString("not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 request instance is publishing 的本地化字符串。
        /// </summary>
        internal static string request_instance_is_publishing {
            get {
                return ResourceManager.GetString("request_instance_is_publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 request session is publishing 的本地化字符串。
        /// </summary>
        internal static string request_session_is_publishing {
            get {
                return ResourceManager.GetString("request_session_is_publishing", resourceCulture);
            }
        }
    }
}
